# This is the project specific Settings.yml file.
# Place Sphinx specific build information here.
# Settings given here will replace the settings of 'conf.py'.

---
conf.py:
  copyright: 2008-2022
  project: File List
  version: 2.6
  release: 2.6.0
  latex_documents:
  - - Index
    - file_list.tex
    - File List
    - Xavier Perseguers
    - manual
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
  intersphinx_mapping:
    t3tsref:
    - https://docs.typo3.org/m/typo3/reference-typoscript/master/en-us/
    - null
  extensions:
    - sphinx.ext.intersphinx
    - t3sphinx.ext.t3extras
    - t3sphinx.ext.t3tablerows
    - t3sphinx.ext.targets
...
